### ISSUE TITLE
Override time ticking (elapsedTime)

### ISSUE THREAD

**Issue by SaadBazaz** [georapbox/canvas-circular-countdown#26]
Hey there,
First of all - thanks for making this library and hitting the nail right in the head. 

## My requirement
A server maintains the duration and elapsed time. I use sockets to sync with it. 
Long story short, I have a ```duration``` and ```elapsedTime``` which is maintained outside of canvas-circular-countdown. I want canvas-circular-countdown to use the elapsedTime which I provide.

## Possible ways to solve this
1. Add another Option called ```time``` which contains the remaining time (pass by reference). Use it simply to display. Or...
2. Expose a method in ```instance``` called "setTime". That way we could use setTime whenever the server timer changes.

Open to more solutions.

**Comment by georapbox** [comment]
Hi @SaadBazaz ,

First of all thanks for your kind words. I'm glad you find this library helpful.

Your issue is a legit one. So, if I understand right, you would like to have a way to update both `duration` and `elapsedTime` while the counter running, which is not supported now out of the box.

If that's the case, what's your opinion if I added 2 instance methods for updating these values, like `.setDuration(time)` and `setElapsedTime(time)`? This way you can call any or both of these methods any time you want to update those values. Do you think that something like would work?

Example:

```js
const countdown = new CanvasCircularCountdown(document.getElementById('canvas'), {
  duration: 60 * 1000,
  elapsedTime: 0
}).start();

// Some time later, when you sync with server...
countdown.setDuration(40 * 1000);
countdown.setElapsedTime(10 * 1000);
```

As a workaround until a proper solution is provided, I would propose to create a new instance of the counter when needed. Please consider the example below:

```js
const options = {
  progressBarWidth: 15,
  progressBarOffset: 5,
  circleBackgroundColor: '#ffffff',
  duration: 60 * 1000,
  elapsedTime: 0
};

let countdown = new CanvasCircularCountdown(document.getElementById('canvas'), options).start();

// Some time later, when you sync with server...
countdown.reset();

countdown = new CanvasCircularCountdown(document.getElementById('canvas'), {
  ...options, // Ensure you keep any previous options
  duration: 40 * 1000, // Override duration
  elapsedTime: 10 * 1000 // Override elapsed time
}).start();
```

**Comment by SaadBazaz** [comment]
Thanks for the quick and comprehensive response! I love your motivation. 

My thoughts on the proposed fixes...

Option 2:
Creating a new instance each time might be memory and compute expensive, specially in our scenario it's quite critical. 

Option 1: 
This sounds great for the time being!
I've made a PR which sets the time through a setTime (#27). I obviously just edited it on GitHub 😅 so it might not be according to your standard.

setElapsedTime and setDuration are even better!

Later on we should explore ways to directly have a referenced variable do the updates. And this library just do the *displaying* part.

**Comment by georapbox** [comment]
I totally agree on creating a new instance that it's not a viable and long-term solution, it's just a workaround until a more appropriate solution is provided.

In the meantime, I had some free time today and I was able to work a little on the issue. I have created a branch [issue-26](https://github.com/georapbox/canvas-circular-countdown/tree/issue-26) that implements the proposed solution with those 2 instance methods I mentioned in previous comment. It's a WIP, hopefully I will have time to work a little more on that on Monday and maybe test any edge cases that I might be missing now.

Your PR was to the right direction, but as you'll notice from the changes I've made a mini refactor so that I avoid duplications.

Hopefully, you can test the library locally with those changes and I would be really interested in your feedback, if this kind of solution meets your requirements.

Thanks!

**Comment by SaadBazaz** [comment]
Thanks so much. I like the way you document your code. 

I'll be trying it first thing in the morning (i.e. 10 hours away) and will let you know.

**Comment by SaadBazaz** [comment]
@georapbox Your solution worked for now <3 Let's keep improving this. I have tonnes of more ideas. 

I request for the issues-26 branch to be pushed to prod and updated on NPM so I can deploy to prod.

**Comment by georapbox** [comment]
Hi there,

PR #28 is merged in master and published in npm.

Thanks for the contribution.
